version: '3.8'

services:

  # Redis  
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    ports:
      - "6379:6379"
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    mem_limit: 256m
    cpus: 0.3
      
  # Application Service
  app:
    container_name: flask
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
    restart: unless-stopped
    ports:
      - "8000:5000"
    depends_on:
      - redis
    mem_limit: 256m
    cpus: 0.3

  test:
    image: curlimages/curl:7.88.1
    command: /bin/sh -c "sleep 10 && curl -s http://app:5000/ -i -vvv"
    depends_on:
      - app
